name: NuGet

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@vmaster
      with:
        dotnet-version: 3.1.100
        source-url: https://nuget.pkg.github.com/Aragas/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Build
      run: dotnet build --configuration Release
      
    - name: Pack
      run: dotnet pack --configuration Release -o "./packages"
      
    - name: Publish
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: dotnet nuget push -s https://nuget.pkg.github.com/Aragas -k $NUGET_AUTH_TOKEN ./packages/*.nupkg
